name: build_pr_ubuntu_gcc_x86_64_riscv_cl3-0
description: Build pr ubuntu_gcc_x86_64_riscv_cl3-0

inputs:
  cache_seed:
    type: boolean
    default: false
  build_targets:
    type: string
    default: 'check-ock'
  disable_unitcl_vecz_checks:
    type: string
    default: 'ON'
  opencl_cts_install:
    type: string
    required: true

runs:
  using: "composite"
  steps:
      - name: remove any old dirs
        shell: bash  
        run:
          rm -rf build

      - name: build ock
        uses: ./.github/actions/do_build_ock
        with:
          build_targets: ${{ inputs.cache_seed == 'true' && 'UnitCL clc' || inputs.build_targets }}
          mux_targets_enable: riscv
          mux_compilers_enable: refsi_m1
          riscv_enabled: ON
          disable_unitcl_vecz_checks: ${{ inputs.disable_unitcl_vecz_checks }}
          enable_rvv_scalable_vecz_check: ON
          enable_rvv_scalable_vp_vecz_check: ON
          host_enable_builtins: OFF
          use_linker: gold
          hal_description: RV64GCV
          hal_refsi_soc: M1
          hal_refsi_thread_mode: WG
          debug_support: ON
          external_compiler_dirs: "${{ github.workspace }}/examples/refsi/refsi_m1/compiler/refsi_m1"
          extra_flags: -DCA_BUILTINS_TOOLS_DIR=${{ github.workspace }}/llvm_install/bin

      - name: run_cities call and run
        run: |
          set -x
          python3 ${{ github.workspace }}/scripts/testing/run_cities.py \
            -s ${{ github.workspace }}/scripts/jenkins/cts_summary/opencl_conformance_tests_wimpy_very_quick.csv \
            -b ${{ inputs.opencl_cts_install }} \
            -e "CA_RISCV_VF=1,S" \
            -L ${{ github.workspace }}/build/lib \
            -e OCL_ICD_FILENAMES=${{ github.workspace }}/build/lib/libCL.so \
            -e OCL_ICD_VENDORS=/dev/null \
            --timeout 00:10:00 \
            --verbose \
            -l ${{ github.workspace }}/build/cts.log -f ${{ github.workspace }}/build/cts.fail -r ${{ github.workspace }}/build/cts_riscv_1s.xml
          ninja -C ${{ github.workspace }}/build check-ock
