name: build_ubuntu_gcc_aarch64_llvm_latest_cl3_0_fp16
description: Build pr ubuntu_gcc_aarch64_llvm_latest_cl3_0_fp16

inputs:
  cache_seed:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
      - name: remove any old dirs
        shell: bash  
        run:
          rm -rf build
      - name: build ock
        uses: ./.github/actions/do_build_ock
        with:
          build_targets: ${{ inputs.cache_seed == 'true' && 'UnitCL clc' || 'check-ock-cross' }} 
          host_fp16: ON
          use_linker: gold
          debug_support: ON
          builtin_kernel: ON
          enable_api: ""
          toolchain_file: "scripts/../platform/arm-linux/aarch64-toolchain.cmake"
          extra_flags: -DCA_BUILTINS_TOOLS_DIR=${{ github.workspace }}/llvm_install_native/bin
          offline_kernel_tests: ${{ inputs.cache_seed == 'true' && 'OFF' || 'ON' }}
