name: upload artifact
description: upload an artifact, tarring first if necessary

inputs:
  name:
    description: 'name of artifact to upload'
    type: string
    required: true
  path:
    description: 'path to upload'
    type: string
    required: true
  needs_tar:
    description: 'dictates whether we tar it first'
    type: boolean
    default: false
  tar_name:
    description: 'Specify name of tar file'
    type: string
    default: ${{ inputs.name }}.tar
  delete_tar:
    description: 'dictates whether we delete temp tar file after upload'
    type: boolean
    default: true
  retention-days:
    description: 'number of days to retain'
    type: string
    default: 7

runs:
  using: "composite"
  steps:
    - name: tar artefacts
      shell: bash
      if: inputs.needs_tar == 'true'
      run: |
        echo Create tar file ...
        set -x
        tar cf ${{ inputs.tar_name }} -C ${{ inputs.path }} .

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.needs_tar == 'true' && inputs.tar_name || inputs.path }}
        retention-days: ${{ inputs.retention-days }}

    - name: delete tar file
      shell: bash
      if: inputs.needs_tar == 'true' && inputs.delete_tar == 'true'
      run: |
        echo Delete tar file ...
        set -x
        rm -rf ${{ inputs.tar_name }}

