name: upload artifact
description: upload an artifact, tarring first if necessary

inputs:
  name:
    description: 'name of artifact to upload'
    type: string
    # ALAN TODO: use required: here?
    default: "none"
  path:
    description: 'path to upload'
    type: string
    required: true
  needs_tar:
    description: 'dictates whether we tar it first'
    type: boolean
    default: false
  retention-days:
    description: 'number of days to retain'
    type: string
    default: 7

runs:
  using: "composite"
  steps:
    - name: tar artefacts
      shell: bash
      if: inputs.needs_tar == 'true'
      run: |
        # ALAN TODO: use inputs: name rather than tmp here?
        tar cf tmp.tar -C ${{ inputs.path }} .

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        # ALAN TODO: use inputs: name rather than tmp here?
        path: ${{ inputs.needs_tar == 'true' && 'tmp.tar' || inputs.path }}
        retention-days: ${{ inputs.retention-days }}
