name: build_pr_ubuntu_gcc_x86_64_riscv_cl3-0_part2
description: Build pr ubuntu_gcc_x86_64_riscv_cl3-0_part2

inputs:
  cache_seed:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
      - name: remove any old dirs
        shell: bash  
        run:
          rm -rf build

      - name: build ock
        uses: ./.github/actions/do_build_ock
        with:
          build_targets: ${{ inputs.cache_seed == 'true' && 'UnitCL clc' || 'check-ock-UnitCL-group-vecz' }}
          mux_targets_enable: riscv
          mux_compilers_enable: refsi_m1
          riscv_enabled: ON
          disable_unitcl_vecz_checks: OFF
          enable_rvv_scalable_vecz_check: ON
          enable_rvv_scalable_vp_vecz_check: ON
          host_enable_builtins: OFF
          use_linker: gold
          hal_description: RV64GCV
          hal_refsi_soc: M1
          hal_refsi_thread_mode: WG
          debug_support: ON
          offline_kernel_tests: OFF
          external_compiler_dirs: "${{ github.workspace }}/examples/refsi/refsi_m1/compiler/refsi_m1"
          extra_flags: -DCA_BUILTINS_TOOLS_DIR=${{ github.workspace }}/llvm_install/bin
