name: setup-ubuntu-build
description: Setup ubuntu ready for building. Includes installs, ninja, build cache setup and loading llvm cache

inputs:
  llvm_build_type:
    description: 'llvm Build type (Release, RelAssert) - note we need to use RelAssert for the cache pattern matching'
    default: RelAssert
  llvm_version:
    description: 'Major llvm version to use for fetching llvm cache e.g. 17'
    default: 17
  ubuntu_version:
    description: 'Version of ubuntu'
    default: 22.04
  save:
    description: 'Save the build cache at the end - not for PR testing'
    default: false


runs:
  # We don't want a new docker just a list of steps, so mark as composite
  using: "composite"
  steps:
    - name: Install prerequisites
      shell: bash    
      env:
        UBUNTU_VER : '${{ inputs.ubuntu_version }}'
      run: |
        sudo apt-get install -y spirv-tools doxygen
        pip install lit clang-format==17.0.6 virtualenv
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        if [ "$UBUNTU_VER" = "20.04" ]; then sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.243-focal.list https://packages.lunarg.com/vulkan/1.3.243/lunarg-vulkan-1.3.243-focal.list; fi
        if [ "$UBUNTU_VER" = "22.04" ]; then sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.243-jammy.list https://packages.lunarg.com/vulkan/1.3.243/lunarg-vulkan-1.3.243-jammy.list; fi
        if [ "$UBUNTU_VER" = "24.04" ]; then sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list https://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list; fi
        sudo apt-get update
        sudo apt-get install --yes vulkan-sdk
        sudo apt-get install --yes gcc-11-multilib g++-11-multilib libtinfo-dev lib32tinfo-dev

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - name: load llvm
      uses: actions/cache/restore@v3
      with:
        path: llvm_install/**
        key: llvm-ubuntu-${{ inputs.ubuntu_version }}-v${{ inputs.llvm_version}}-${{ inputs.llvm_build_type }}
        fail-on-cache-miss: true

      # note the PR testing usage should set 'save' to false, to avoid PR testing creating new caches on a branch
    - name: Setup sccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 200M
        key: sccache-build
        variant: sccache
        save: ${{ inputs.save }}
 
