name: build sycl cts
description: build sycl cts

inputs:
  target:
    description: 'target architecture'
  sycl_device:
    description: '"ock" or "native_cpu"'
    default: 'ock'
  download_sycl_cts_artefact:
    description: 'download ock artefact rather than building, of form <target>=id;<target2=id2>.'
    default: ''    

runs:
  using: "composite"
  steps:
    - name: calc vars
      id: calc_vars
      uses: ./.github/actions/calc_vars
      with:
        target: ${{ inputs.target }}  

    - name: Install Ninja
      if: contains(inputs.download_sycl_cts_artefact, inputs.target) != true
      uses: llvm/actions/install-ninja@main

    - name: download icd artifact
      if: inputs.sycl_device == 'ock' && contains(inputs.download_sycl_cts_artefact, inputs.target) != true
      uses: actions/download-artifact@v4
      with:
        name: icd_${{inputs.target}}
        path: install_icd

    - name: download headers artifact
      if: inputs.sycl_device == 'ock' && contains(inputs.download_sycl_cts_artefact, inputs.target) != true
      uses: actions/download-artifact@v4
      with:
        name: header_${{inputs.target}}
        path: install_headers

    - name: download dpc++ artifact
      if: contains(inputs.download_sycl_cts_artefact, inputs.target) != true
      uses: actions/download-artifact@v4
      with:
        name: dpcpp_${{inputs.target}}
        path: install_dpcpp

    - name: unpackage dpc++ artifacts # package/unpackage avoids known 'permissions loss' issue
      if: contains(inputs.download_sycl_cts_artefact, inputs.target) != true
      shell: bash
      run: |
        cd install_dpcpp
        tar xf dpcpp.tar
        rm dpcpp.tar

    - name: checkout sycl cts
      if: contains(inputs.download_sycl_cts_artefact, inputs.target) != true
      uses: actions/checkout@v4
      with:
        repository: KhronosGroup/SYCL-CTS
        path: SYCL-CTS.src
        submodules: true

    - name: build SYCL CTS
      if: contains(inputs.download_sycl_cts_artefact, inputs.target) != true    
      shell: bash
      run: |
        echo calling cmake and ninja on SYCL CTS
        # Todo: as we extend into cross etc, we may want to expand on the cxx flags
        # We build SYCL-CTS without installing it, so build directly in the top level.
        git -C SYCL-CTS.src log -1
        for patch in $GITHUB_WORKSPACE/scripts/testing/patches/SYCL-CTS-*.patch
        do
          if test -f "$patch"
          then
            echo "Applying ${patch##*/}"
            git -C SYCL-CTS.src apply "$patch"
          fi
        done
        if [[ "${{inputs.sycl_device}}" = "ock" ]] ; then
          DEV_OPTS="-DOpenCL_LIBRARY=$GITHUB_WORKSPACE/install_icd/lib/libOpenCL.so -DOpenCL_INCLUDE_DIR=$GITHUB_WORKSPACE/install_headers/include"
        else # native_cpu
          DEV_OPTS="-DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=OFF -DDPCPP_FLAGS='-fsycl-targets=native_cpu'"
        fi
        export JOPT="4"
        if [[ "${{inputs.target}}" =~ .*aarch64.* ]] ; then # needed for cp-graviton runner
          JOPT="2"
        fi
        set -x
        cmake -S SYCL-CTS.src \
            -GNinja \
            -B SYCL-CTS \
            -DSYCL_IMPLEMENTATION=DPCPP \
            -DDPCPP_INSTALL_DIR=$GITHUB_WORKSPACE/install_dpcpp \
            -DCMAKE_CXX_COMPILER="$GITHUB_WORKSPACE/install_dpcpp/bin/clang++" \
            -DCMAKE_CXX_FLAGS="--target=${{steps.calc_vars.outputs.arch}}-linux-gnu" \
            -DCMAKE_CXX_LINK_FLAGS="-fuse-ld=lld" \
            ${DEV_OPTS}
        ninja -C SYCL-CTS -v -j$JOPT -k 0 || :

    - name: package artefacts  # package/unpackage avoids known 'permissions loss' issue
      if: contains(inputs.download_sycl_cts_artefact, inputs.target) != true    
      shell: bash
      run: |
        cd SYCL-CTS
        # only bin
        tar cf sycl-cts.tar bin

    - name: download sycl cts artefact  # package/unpackage avoids known 'permissions loss' issue
      if: contains(inputs.download_sycl_cts_artefact, inputs.target)
      shell: bash
      run: |
        download_id=`echo "${{inputs.download_sycl_cts_artefact}}"`
        echo "echo $download_id | sed 's/.*${{inputs.target}}=//' | sed 's/;.*//'"
        download_id=`echo $download_id | sed 's/.*${{inputs.target}}=//' | sed 's/;.*//'`
        echo download id is "'$download_id'"
        # TODO : make this work on windows
        mkdir -p SYCL-CTS
        git config --global --add safe.directory $PWD        
        gh run download $download_id -n sycl_cts_${{ inputs.sycl_device }}_${{ inputs.target }} -D SYCL-CTS
        ls SYCL-CTS


    - name: upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: sycl_cts_${{inputs.sycl_device}}_${{inputs.target}}
        path: SYCL-CTS/sycl-cts.tar
        retention-days: 7
  
