name: build run sanitizers
description: build run sanitizers

runs:
  # We don't want a new docker just a list of steps, so mark as composite
  using: "composite"
  steps:
    #
    # tsan
    #
    - name: Checkout repo llvm
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        #ref: ${{inputs.llvm_branch}}
        ref: 'release/19.x'  # ALAN TODO: pass in param for this
        #path: llvm-project
        path: llvm-project
    - name: Install Ninja
      uses: llvm/actions/install-ninja@a1ea791b03c8e61f53a0e66f2f73db283aa0f01e # main branch
    - name: Run cmake
      shell: 'bash'
      run: |
        echo PATH IS $PATH
        ls -l /usr/bin
        ls -l
        cmake llvm-project/llvm \
            -GNinja \
            -Bbuild \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/llvm_install \
            -DCA_LLVM_PROJECT_DIR=$GITHUB_WORKSPACE/llvm-project \
            -DCA_LLVM_SPIRV_PROJECT_DIR=$GITHUB_WORKSPACE/llvm-spirv \
            -DLLVM_ENABLE_ZLIB=FALSE \
            -DLLVM_ENABLE_Z3_SOLVER=FALSE \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLLVM_USE_SANITIZER=Thread \
            -DCMAKE_C_COMPILER=/usr/bin/clang-19 \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-19
        ls -l
        #cmake llvm-project/llvm
        #    -DLLVM_ENABLE_DIA_SDK=OFF
        #    -DCMAKE_INSTALL_PREFIX=llvm_install
        #    -DLLVM_ENABLE_ZLIB=FALSE
        #    -DLLVM_ENABLE_ZSTD=FALSE
        #    -DLLVM_ENABLE_Z3_SOLVER=FALSE
        #    -DLLVM_ENABLE_PROJECTS="clang;lld"
        #    -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;RISCV"
        #    -Bbuild
        #    -GNinja
        #    -DCMAKE_BUILD_TYPE=Release
        #    ${{ inputs.build_type == 'RelAssert' && '-DLLVM_ENABLE_ASSERTIONS=ON' || '' }}
        #    ${{ !startsWith(runner.os, 'Windows') && '-DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON' || '' }}
        #    $ARCH_FLAGS
    - name: Run build on llvm
      shell: 'bash'
      run:
        cmake --build $GITHUB_WORKSPACE/build --target install -- -j4
        #cmake --build build --target install
    # build/run OCK
