name: build_pr_ubuntu_clang_x86_llvm_latest_cl3_0
description: Build pr ubuntu_clang_x86_llvm_latest_cl3_0

inputs:
  cache_seed:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
      - name: remove any old dirs
        shell: bash  
        run:
          rm -rf build

      - name: build ock x86 relassert
        uses: ./.github/actions/do_build_ock
        with:
          build_32_bit: ON
          build_targets: ${{ inputs.cache_seed == 'true' && 'UnitCL clc' || 'check-ock' }}
          builtin_kernel: ON
          debug_support: ON
          offline_kernel_tests: 'OFF'
          toolchain_file: $GITHUB_WORKSPACE/platform/x86-linux/x86-toolchain.cmake
          extra_flags: -DCMAKE_CROSSCOMPILING=TRUE -DCA_EXTERNAL_BUILTINS=FALSE -DCA_BUILTINS_TOOLS_DIR=$GITHUB_WORKSPACE/llvm_install/bin -DCMAKE_C_COMPILER=$GITHUB_WORKSPACE/llvm_install/bin/clang -DCMAKE_CXX_COMPILER=$GITHUB_WORKSPACE/llvm_install/bin/clang++
