name: build run remote_hal
description: build run remote_hal

runs:
  # We don't want a new docker just a list of steps, so mark as composite
  using: "composite"
  steps:
    - name : build server
      shell: bash
      run: |
        echo build_server
        mkdir build_server
        cmake -GNinja $GITHUB_WORKSPACE/examples/hal_cpu_remote_server -Bbuild_server -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/platform/riscv64-linux/riscv64-gcc-toolchain.cmake
        ninja -Cbuild_server
    - name : build client
      shell: bash
      run: |
        ls -l
        echo build_client
        cmake -Bbuild_client -GNinja -DCA_MUX_TARGETS_TO_ENABLE="riscv" -DCA_RISCV_ENABLED=ON -DCA_LLVM_INSTALL_DIR=$GITHUB_WORKSPACE/llvm_install -DCA_CL_ENABLE_ICD_LOADER=ON -DCA_HAL_NAME=cpu_client
        ninja -Cbuild_client UnitCL
    - name : run remote_hal
      shell: bash
      run: |
        echo run remote_hal
