name: build_pr_ubuntu_gcc_x86_64_refsi_g1_wi_cl3_0
description: Build pr ubuntu_gcc_x86_64_refsi_g1_wi_cl3_0

inputs:
  cache_seed:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
      - name: remove any old dirs
        shell: bash  
        run:
          rm -rf build
      - name: build ock
        uses: ./.github/actions/do_build_ock
        with:
          build_targets: install # Build the install target so we don't miss compilation errors
          mux_targets_enable: riscv
          external_compiler_dirs: ${{ github.workspace }}/examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi
          mux_compilers_enable: refsi_g1_wi
          riscv_enabled: ON
          disable_unitcl_vecz_checks: ON
          enable_rvv_scalable_vecz_check: ON
          enable_rvv_scalable_vp_vecz_check: ON
          use_linker: gold
          hal_description: RV64GCV
          hal_refsi_soc: G1
          hal_refsi_thread_mode: WI
          debug_support: ON
          offline_kernel_tests: ${{ inputs.cache_seed == 'true' && 'OFF' || 'ON' }} 
