# Cache clean workflow

name: Cache clean

on:
  #schedule:
  #  # Run Mon-Fri at 7pm
  #  - cron: '00 19 * * 1-5'
  workflow_dispatch:
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clean_cache:
    name: Cache clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.0
      - name: Cache clean
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache --help
          gh actions-cache list --help
          gh actions-cache delete --help
          gh actions-cache list -B main -L 100 --order desc --sort created-at
          #for cache_prefix in llvm-ubuntu- sccache-sccache- ; do gh actions-cache list -B main -L 100 --order desc --sort created-at | grep -E -o "^${cache_prefix}[^[:space:]]+" | sed '1d' ; done
          for cache_prefix in llvm-ubuntu- codeql-trap- sccache-sccache- ; do gh actions-cache list -B main -L 100 --order desc --sort created-at | grep -E -o "^${cache_prefix}[^[:space:]]+" | sed '1d' ; done
