# Cache clean workflow

name: Cache clean

on:
  #schedule:
  #  # Run Mon-Fri at 7pm
  #  - cron: '00 19 * * 1-5'
  workflow_dispatch:
   inputs:
      dryrun:
        required: true
        type: boolean
        default: false
  pull_request:
  push:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clean_cache:
    name: Cache clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.0
      - name: Cache clean
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          #gh actions-cache --help
          #gh actions-cache list --help
          #gh actions-cache delete --help
          echo BEFORE ...
          gh actions-cache list -B main -L 100 --order asc --sort created-at | tee CACHE_LIST
          PREFIX_LIST="llvm-ubuntu- codeql-trap- sccache-sccache-"
          DELETE_LIST=$(for CACHE_PREFIX in $PREFIX_LIST ; do grep -E -o "^${CACHE_PREFIX}[^[:space:]]+" CACHE_LIST| sed '1d' ; done)
          echo DELETIONS ...
          echo DRYRUN ... ${{ inputs.dryrun }}
          for CACHE in $DELETE_LIST; do echo DELETING $CACHE ; done
          echo AFTER ...
          gh actions-cache list -B main -L 100 --order asc --sort created-at
