# Temporary for testing - move to planned_testing_caller.yml
name: Run ock tests for PR style testing
on:
  pull_request:
    paths:
      - '.github/workflows/create_llvm_artefacts.yml'
      - '.github/workflows/create_llvm_artefacts_caller.yml'
  schedule:
    # Run Mon-Fri at 7pm
    - cron: '00 19 * * 1-5'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_llvm_artefacts:
    name: Call PR testing on schedule
    if: ${{ (github.event_name == 'schedule' && github.repository == 'uxlfoundation/oneapi-construction-kit') || github.event_name == 'pull_request' }}
    permissions:
      actions: write
    uses: ./.github/workflows/create_llvm_artefacts.yml
    secrets: inherit
    with:
      llvm_branch: 'release/19.x'
      llvm_branch_id: '19'

  use_llvm_artefacts:
    needs: [build_llvm_artefacts]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: set up gh
        uses: ./.github/actions/setup_gh
        with:
          os: ${{ contains( matrix.target, 'windows') && 'windows' || 'ubuntu' }}
          token: ${{ secrets.GITHUB_TOKEN }}     
      - name: Try downloading llvm install
        run: |
          echo workflow id is ${{needs.build_llvm_artefacts.outputs.workflow_id}}
          # TODO: We need to add tarring there and here
          gh run download ${{github.run_id}} -n llvm-ubuntu-22.04-x86_64-19-RelAssert -D llvm_install
          ls -l llvm_install/bin
