name: Test CI - Multi-Line Value
on:
  #pull_request:
  workflow_dispatch:
    paths: 
    - .github/workflows/envtest.yml

jobs:
  set_opencl_cts_path:
    runs-on: ubuntu-latest
    outputs:
      path_spec: ${{ steps.path_id.outputs.OPENCL_CTS_PATH }}
    steps:
      - name: set var
        id: path_id
        run: |
          echo "OPENCL_CTS_PATH<<EOF" >> $GITHUB_OUTPUT
          # PATH START ...
          echo 'test_conformance' >> $GITHUB_OUTPUT
          echo '!test_conformance/**/.*' >> $GITHUB_OUTPUT
          echo '!test_conformance/**/CMakeCache.txt' >> $GITHUB_OUTPUT
          echo '!test_conformance/**/CMakeFiles' >> $GITHUB_OUTPUT
          echo '!test_conformance/**/CMakeFiles/**' >> $GITHUB_OUTPUT
          echo '!test_conformance/**/*.cmake' >> $GITHUB_OUTPUT
          echo '!test_conformance/**/*.ninja' >> $GITHUB_OUTPUT
          echo '!test_conformance/test_common' >> $GITHUB_OUTPUT
          echo '!test_conformance/test_common/**' >> $GITHUB_OUTPUT
          # ... PATH END
          echo "EOF" >> $GITHUB_OUTPUT

  use_opencl_cts_path:
    needs: [set_opencl_cts_path]
    runs-on: ubuntu-latest
    env:
      OPENCL_CTS_PATH: ${{ needs.set_opencl_cts_path.outputs.path_spec }}
    steps:
      - name: download cached opencl_cts artifact
        uses: actions/cache/restore@v4
        with:
          key: opencl_cts_host_x86_64_linux
          path: |
            ${{ env.OPENCL_CTS_PATH }}
          fail-on-cache-miss: true
