name: Test CI - Multi-Line Value
on:
  pull_request:
    paths: 
    - .github/workflows/envtest.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Defining a new Environment Variable
        id: alan_step
        run: |                          
          {
          echo 'ALAN_VAR<<EOF'
          curl https://example.com
          curl https://example.com
          curl https://example.com
          echo EOF
          } >> "$GITHUB_ENV"
          
      - name: Using the previously defined environment variable
        env:
          ALAN_STR: ${{ steps.alan_step.outputs.ALAN_VAR }} 
        run: |
          echo "$ALAN_STR"
