name: Test CI - Multi-Line Value
on:
  pull_request:
    paths: 
    - .github/workflows/envtest.yml

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      alan-op: ${{ steps.alan-id.outputs.ALAN_VAR }}
    steps:
      - name: set var
        id: alan-id
        run: |
          echo "ALAN_VAR=hello" >> $GITHUB_OUTPUT

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    env:
      ALAN_ENV: ${{ needs.job1.outputs.alan-op }}
    steps:
      - name: print var
        id: alan-id
        run: |
          echo "ALAN_VAR=$ALAN_ENV"
      - name: download cached opencl_cts artifact
        uses: actions/cache/restore@v4
        with:                                                                                                                key: opencl_cts_host_x86_64_linux
          path: |
            ${{ env.ALAN_ENV }}
          #path: |
          #  test_conformance
          #  !test_conformance/**/.*
          #  !test_conformance/**/CMakeCache.txt
          #  !test_conformance/**/CMakeFiles
          #  !test_conformance/**/CMakeFiles/**
          #  !test_conformance/**/*.cmake
          #  !test_conformance/**/*.ninja
          #  !test_conformance/test_common
          #  !test_conformance/test_common/**
          fail-on-cache-miss: true
    
