name: Test CI - Multi-Line Value
on:
  pull_request:
    paths: 
    - .github/workflows/envtest.yml

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      alan-op: ${{ steps.alan-id.outputs.ALAN_VAR }}
    steps:
      - name: set var
        id: alan-id
        run: |
          echo "ALAN_VAR=hello" >> $GITHUB_OUTPUT

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    env:
      ALAN_ENV: ${{ needs.job1.outputs.alan-op }}
    steps:
      - name: print var
        id: alan-id
        run: |
          echo "ALAN_VAR=$ALAN_ENV"
    
