name: run planned tests for llvm 19
on:
  #pull_request:
  workflow_dispatch:
    paths:
      - '.github/workflows/planned_testing_caller_19.yml'
  schedule:
    # Run Sun, Tues, Thurs Sat at 7pm
    - cron: '0 19 * * 0,2,4,6'

permissions:
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  L19_:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    uses: ./.github/workflows/planned_testing_caller.yml
    with:
      llvm_version: '19'
      llvm_branch: 'release/19.x'
      use_llvm_github_cache: true
      # We can set ock, test_sycl_cts etc here optionally if this is used as a pull request.
      # Any with parameters below this is intended for local testing and should not be merged.
      # ALAN TODO: set target for artifact build here - massage PR jobs that use any other
      target_list: '[ "host_x86_64_linux" ]'
      # ock: true
      native_cpu: false
      test_tornado: false
      test_remote_hal: false
      test_sycl_cts: false
      test_sycl_e2e: false
      test_opencl_cts: false
      # run_internal: true
      # run_external: true
      # build_llvm: true
      # ALAN TODO: add opencl_cts artifact as "test" type
      # opencl_cts_artifact: true

      # # These can be set to a workflow run-id to download from a previous workflow. This can be seen from
      # # the action run of a job or workflow
      # # e.g. https://github.com/uxlfoundation/oneapi-construction-kit/actions/runs/<run-id>/.....
      # download_ock_artefact: host_x86_64_linux=14225268091;host_aarch64_linux=14225268091;host_riscv64_linux=14225268091
      download_ock_artefact: host_x86_64_linux=15713431354
      # download_dpcpp_artefact: host_x86_64_linux=14225268091;host_aarch64_linux=14225268091;host_riscv64_linux=14225268091
      # download_sycl_cts_artefact: host_x86_64_linux=14225268091;host_aarch64_linux=14225268091;host_riscv64_linux=14225268091

# Force running L19 on PR
