name: run planned tests for llvm 20
on:
  pull_request:
    paths:
      - '.github/workflows/planned_testing_caller_20.yml'
  schedule:
    # Run Mon, Wed, Fri at 7pm
    - cron: '0 19 * * 1,3,5'

# To add another llvm planned testing, simply copy this file and set the llvm_version and llvm_branch variables
# llvm_version is only used for tagging purposes, although ideally would be a number or main
# We may want to delete the lowest version for planned_testing_caller_*.yml at that time.
# If it is known to be unchanging, then set the 'use_llvm_github_cache: true' as an input to planned_testing_caller.yml/

# Note this will not affect normal PR runs which will require run_pr_tests_caller.yml to be updated.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # This makes the diagram too big if we post much here so L20_ is used.
  L20_:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    uses: ./.github/workflows/planned_testing_caller.yml
    with:
      llvm_version: '20'
      llvm_branch: 'release/20.x'
      # We can set ock, test_sycl_cts etc here optionally if this is used as a
      # pull request. Any parameters below this is intended for local testing
      # and should not be merged nor reviewed (other than checking it should not be merged).
      # extras here


