name: Seed the cache for ock builds
on:
  # pull_request:
  #   paths:
  #     - '.github/workflows/pr_tests_cache.yml'
  push:
    branch: main
    paths:    
      - 'source/**'
      - 'clik/**'
      - 'modules/**'
      - 'examples/**'
      - 'cmake/**'
      - 'hal/**'
      - '.github/workflow/pr_tests_cache.yml'
      - '.github/actions/do_build_ock/**'
      - '.github/actions/setup_build/**'
      - '.github/action/do_build_pr/**'
      - 'CMakeLists.txt'

  workflow_dispatch:

env:
  llvm_previous: '18'
  llvm_current: '19'

concurrency:
  group: pr-test-cache-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
jobs:
  ubuntu_22_llvm_prev_jobs:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/uxlfoundation/ock_ubuntu_22.04-x86-64:latest
      volumes:
        - ${{github.workspace}}:${{github.workspace}}    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup ubuntu
        uses: ./.github/actions/setup_build
        with:
          llvm_version: ${{ env.llvm_previous }}
          llvm_build_type: RelAssert
          save: true

      - name: build host_x86_64
        uses:  ./.github/actions/do_build_pr/run_host_x86_64
        with:
          cache_seed: true

      - name: build riscv M1
        uses: ./.github/actions/do_build_pr/run_riscv_m1
        with:
          cache_seed: true

      - name: build ubuntu_gcc_x86_64_riscv_fp16_cl3_0_unitcl_vecz
        uses: ./.github/actions/do_build_pr/run_ubuntu_gcc_x86_64_riscv_fp16_cl3_0_unitcl_vecz
        with:
          cache_seed: true

  ubuntu_22_llvm_current_jobs:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    needs: [ubuntu_22_llvm_prev_jobs]
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/uxlfoundation/ock_ubuntu_22.04-x86-64:latest
      volumes:
        - ${{github.workspace}}:${{github.workspace}}    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup-ubuntu
        uses:  ./.github/actions/setup_build
        with:
          llvm_version: ${{ env.llvm_current }}
          llvm_build_type: RelAssert
          save: true

      - name: build ubuntu_gcc_x86_64_riscv_fp16_cl3_0
        uses: ./.github/actions/do_build_pr/run_ubuntu_gcc_x86_64_riscv_fp16_cl3_0
        with:
          cache_seed: true
    
      - name: build ubuntu_gcc_x86_llvm_latest_x86_64_images_cl3_0_release
        uses: ./.github/actions/do_build_pr/run_ubuntu_gcc_x86_llvm_latest_x86_64_images_cl3_0_release
        with:
          cache_seed: true

      - name: build ubuntu_gcc_x86_64_refsi_g1_wi_cl3_0
        uses: ./.github/actions/do_build_pr/run_ubuntu_gcc_x86_64_refsi_g1_wi_cl3_0          
        with:
          cache_seed: true

  # 32 bit x86
  ubuntu_22_llvm_current_x86_jobs:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    needs: [ubuntu_22_llvm_current_jobs]  
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/uxlfoundation/ock_ubuntu_22.04-x86-64:latest
      volumes:
        - ${{github.workspace}}:${{github.workspace}}    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # installs tools, ninja, installs llvm and sets up sccache
      - name: setup-ubuntu
        uses:  ./.github/actions/setup_build
        with:
          llvm_version: ${{ env.llvm_current }}
          llvm_build_type: RelAssert
          save: true
          cross_arch: x86

      - name: build ubuntu_clang_x86_llvm_latest_cl3_0_offline
        uses: ./.github/actions/do_build_pr/run_ubuntu_clang_x86_llvm_latest_cl3_0_offline
        with:
          cache_seed: true

  # aarch 64
  ubuntu_22_llvm_current_aarch64_jobs:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    needs: [ubuntu_22_llvm_current_x86_jobs]  
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/uxlfoundation/ock_ubuntu_22.04-x86-64:latest
      volumes:
        - ${{github.workspace}}:${{github.workspace}}    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

        # installs tools, ninja, installs llvm and sets up sccache
      - name: setup-ubuntu
        uses: ./.github/actions/setup_build
        with:
          llvm_version: ${{ env.llvm_current }}
          llvm_build_type: RelAssert
          save: true
          cross_arch: aarch64

      - name: build ubuntu_gcc_aarch64_llvm_latest_cl3_0_fp16
        uses: ./.github/actions/do_build_pr/run_ubuntu_gcc_aarch64_llvm_latest_cl3_0_fp16
        with:
          cache_seed: true

  windows_llvm_current_jobs:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    needs: [ubuntu_22_llvm_current_aarch64_jobs]    
    runs-on: windows-2019
    steps:    
      - name: Setup Windows llvm base
        uses: llvm/actions/setup-windows@main
        with:
          arch: amd64

      - name: Checkout repo
        uses: actions/checkout@v4

      # installs tools, ninja, installs llvm and sets up ccache
      - name: setup-windows
        uses:  ./.github/actions/setup_build
        with:
          llvm_version: ${{ env.llvm_current }}
          llvm_build_type: RelAssert
          save: true
          os: windows
      - name: build windows_msvc_x86_64_llvm_latest_cl3_0_offline
        uses: ./.github/actions/do_build_pr/run_windows_msvc_x86_64_llvm_latest_cl3_0_offline
        with:
          cache_seed: true


  # The following tries to delete old caches but fails on the branch due to permissions errors
  # Look to uncomment in the future.

  # clean_cache:
  #  if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
  #   name: Cache clean
  #   needs: [windows_llvm_current_jobs]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: write
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: .github
  #     - name: Cache clean
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         # Define unique cache prefixes for deletion
  #         CACHE_PREFIX_LIST: "ccache-ccache-build-ubuntu ccache-ccache-build-windows"
  #       run: |
  #         set -x
  #         echo Cache branch name is ${{ github.ref }}
  #         # Define args for gh cache commands
  #         GH_LIST_ARGS="-r ${{ github.ref }} -L 100 --order desc --sort created-at"
  #         echo CACHE PREFIXES FOR CLEANING ... $CACHE_PREFIX_LIST_UBUNTU $CACHE_PREFIX_LIST_WINDOWS
  #         # Generate current cache list for ${{ github.ref_name }}, newest first (note: 100 cache entries is gh maximum)
  #         echo CACHE LIST BEFORE ...
  #         gh cache list $GH_LIST_ARGS | tee CACHE_LIST
  #         echo > CCACHE_LIST


  #         # Generate corresponding list of cache keys for deletion - retain only the newest key for each prefix
  #         for CACHE_PREFIX in $CACHE_PREFIX_LIST
  #         do
  #           grep -E -o "^${CACHE_PREFIX}[^[:space:]]+" CACHE_LIST | sed '1d' >> CCACHE_LIST
  #         done

  #         cat CCACHE_LIST

  #         DELETE_LIST=$(cat CCACHE_LIST)
  #         echo Ubuntu Delete List is $DELETE_LIST, Delete Args = $GH_DELETE_ARGS_KEY
  #         for KEY in $DELETE_LIST ; do  gh cache delete $KEY ; done

  #         # Generate post-clean list
  #         echo CACHE LIST AFTER ...
  #         gh cache list $GH_LIST_ARGS
