name: build opencl cts
description: build opencl cts

inputs:
  target:
    required: true
    type: string
    description: 'target architecture'
  cache_update:
    required: false
    type: boolean
    description: 'flag indicating that a cache update for the built artifact is required'
    default: false
  opencl_cts_ref:
    required: false
    type: string
    description: 'Git checkout ref for OpenCL-CTS repo'
    default: ''

runs:
  using: "composite"
  steps:
    - name: calc vars
      id: calc_vars
      uses: ./.github/actions/calc_vars
      with:
        target: ${{ inputs.target }}

    - name: Install Ninja
      uses: llvm/actions/install-ninja@a1ea791b03c8e61f53a0e66f2f73db283aa0f01e # main branch
    
    - name: download icd artifact
      uses: actions/download-artifact@v4
      with:
        name: icd_${{inputs.target}}
        path: install_icd

    - name: download header artifact
      uses: actions/download-artifact@v4
      with:
        name: header_${{inputs.target}}
        path: install_headers

    - name: checkout test suite
      uses: actions/checkout@v4
      with:
        repository: KhronosGroup/OpenCL-CTS
        path: OpenCL-CTS
        ref: ${{inputs.opencl_cts_ref}}

    - name: build opencl cts
      shell: bash
      env:
        CMAKE_TOOLCHAIN: "${{ steps.calc_vars.outputs.cmake_toolchain }}"
      run: |
        echo CMAKE_TOOLCHAIN is: $CMAKE_TOOLCHAIN
        # apply patches
        git -C OpenCL-CTS log -1
        for patch in $GITHUB_WORKSPACE/scripts/testing/patches/OpenCL-CTS-*.patch
        do
          if test -f "$patch"
          then
            echo "Applying ${patch##*/}"
            git -C OpenCL-CTS apply "$patch"
          fi
        done
        # do build
        set -x
        cmake -G Ninja $CMAKE_TOOLCHAIN $GITHUB_WORKSPACE/OpenCL-CTS \
          -DCMAKE_BUILD_TYPE=Release \
          -DOPENCL_LIBRARIES=OpenCL \
          -DCL_INCLUDE_DIR=$GITHUB_WORKSPACE/install_headers/include \
          -DCL_LIB_DIR=$GITHUB_WORKSPACE/install_icd/lib
        ninja -v

    - name: upload opencl cts artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opencl_cts_${{inputs.target}}
        path: |
          test_conformance
          !test_conformance/**/.*
          !test_conformance/**/CMakeCache.txt
          !test_conformance/**/CMakeFiles
          !test_conformance/**/CMakeFiles/**
          !test_conformance/**/*.cmake
          !test_conformance/**/*.ninja
          !test_conformance/test_common
          !test_conformance/test_common/**
        retention-days: 7

    - name: update opencl cts artifact cache
      if: inputs.cache_update == 'true'
      uses: actions/cache/save@v4
      id: cache
      with:
        key: opencl_cts_${{inputs.target}}
        path: |
          test_conformance
          !test_conformance/**/.*
          !test_conformance/**/CMakeCache.txt
          !test_conformance/**/CMakeFiles
          !test_conformance/**/CMakeFiles/**
          !test_conformance/**/*.cmake
          !test_conformance/**/*.ninja
          !test_conformance/test_common
          !test_conformance/test_common/**
